version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/node"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/node/npm/darwin-arm64"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/darwin-x64"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/linux-arm-gnueabihf"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/linux-arm64-gnu"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/linux-arm64-musl"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/linux-x64-gnu"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/linux-x64-musl"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/win32-arm64-msvc"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/win32-ia32-msvc"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node/npm/win32-x64-msvc"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/node"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/templates/template-blazor/Source"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/worker"
      schedule:
          interval: "daily"
      versioning-strategy: increase
